import java.util.Base64
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.kotlinSerialization)
}

// Generates DefaultServerIcon.kt (a base64 string constant) from the checked-in PNG at
// src/commonMain/assets/default_server_icon.png, so the actual asset — not a hand-typed encoding
// of it — is the thing that lives in version control and gets reviewed/diffed.
val defaultServerIconAsset = layout.projectDirectory.file("src/commonMain/assets/default_server_icon.png")
val generatedDefaultServerIconDir = layout.buildDirectory.dir("generated/defaultServerIcon")

val generateDefaultServerIcon by tasks.registering {
    val inputFile = defaultServerIconAsset.asFile
    val outputDirProvider = generatedDefaultServerIconDir

    inputs.file(inputFile)
    outputs.dir(outputDirProvider)

    doLast {
        val base64 = Base64.getEncoder().encodeToString(inputFile.readBytes())
        val chunks = base64.chunked(100)

        val source = buildString {
            appendLine("package dev.tomatopotato.asterion.servers")
            appendLine()
            appendLine("// GENERATED by the :shared:generateDefaultServerIcon Gradle task from")
            appendLine("// src/commonMain/assets/default_server_icon.png. Do not edit by hand —")
            appendLine("// edit the PNG and rebuild instead.")
            appendLine("object DefaultServerIcon {")
            appendLine("    val base64: String =")
            chunks.forEachIndexed { index, chunk ->
                val suffix = if (index == chunks.lastIndex) "\"" else "\" +"
                appendLine("        \"$chunk$suffix")
            }
            appendLine("}")
        }

        outputDirProvider.get().file("DefaultServerIcon.kt").asFile.apply {
            parentFile.mkdirs()
            writeText(source)
        }
    }
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    android {
        namespace = "dev.tomatopotato.asterion.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
        withHostTest {
        }
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }.configure {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonMain.dependencies {
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.contentNegotiation)
            implementation(libs.ktor.serialization.kotlinxJson)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.coroutines.core)
        }
        commonMain {
            kotlin.srcDir(generateDefaultServerIcon.map { generatedDefaultServerIconDir.get() })
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}
